-- CreateEnum
CREATE TYPE "public"."Specialty" AS ENUM ('DENTIST', 'PEDIATRICIAN', 'PSYCHIATRIST', 'OPHTHALMOLOGIST', 'DERMATOLOGIST');

-- AlterTable
ALTER TABLE "public"."Users" ALTER COLUMN "documentType" SET DEFAULT 'CPF',
ALTER COLUMN "role" SET DEFAULT 'PATIENT';
